services:
  postgres:
    image: postgres:15-alpine
    container_name: ecp_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123258789
      POSTGRES_DB: ecp_pg
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ecp_network
    restart: always
  # MongoDB
  mongo:
    image: mongo:7.0
    container_name: ecp_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - ecp_network
    restart: always
  # Redis cache
  redis:
    image: redis:alpine
    container_name: ecp_redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly #Enable persistent disk saving mode.
    volumes:
      - redis_data:/data
    networks:
      - ecp_network
    restart: always
networks:
  ecp_network:
    driver: bridge
volumes:
  pg_data:
  mongo_data:
  redis_data:
